#!/bin/bash

gcc -g -o compiler \
    main.c \
    lexer.c \
    utils.c \
    parser.c \
    lowering/c.c \
    error.c \
    type_inference.c \
    soundness.c \
    -lm \
    -D DEBUG_CONTEXT

mkdir -p target
./compiler "$1"
# rm compiler
# cd target
# gcc -o bin c_output.c
